### ISSUE TITLE
Répartition

### ISSUE THREAD

**Issue by Jaconil** [siwon/projetBomberman#10]
Je suis en train de faire le diagramme de Gantt là, mais comment on se répartit les modules et la doc à faire ?

On a :
- Contrôleurs : Bibiz
- Menu : Max
- Interface : Max
- Réseau : Brice
- Moteur : Simon
- Son : ?
- Skin : ?
- Configuration : ?

Intégration : Tous ?
Manuel d'installation : Bibiz
Manuel d'utilisation : Simon
Tests de de pré-livraison : Tous ?

**Comment by Jaconil** [comment]
Skin c'est le module de chargement d'images en fonction du skin choisi (cf : Cahier des charges si tu veux savoir)

**Comment by Jaconil** [comment]
et OK pour le manuel

**Comment by siwon** [comment]
Je veux bien faire le manuel d'utilisation si tu veux. Par contre, pour l'intégration et les tests de pré-livraison, ce ne sera pas tout le monde ?

**Comment by siwon** [comment]
O_O Je n'arrive pas à croire que binôme ai accepté les noms de variables avec des pluriels ... Je pense que c'est encore un signe que c'est le début de la fin de notre binômat, parce que moi ça passe pas, par contre avec maxime ça passe ...

Tkt binôme, je comprend ...
