### ISSUE TITLE
Version de la SFML

### ISSUE THREAD

**Issue by abisiaux** [siwon/projetBomberman#12]
C'est SFML 1.6 OU 2.0 qu'il faut utiliser ?

Car dans la 2.0, pour gérer le clavier je n'aurais pas besoin du sf::RenderWindow idem pour le joystick...

**Comment by Jaconil** [comment]
La version stable actuelle est la 1.6.

Je vais tenter de regarder les nouveautés de la version 2 ce soir, quand j'aurai fini XML.

**Comment by abisiaux** [comment]
Je continu sur la 2.0 car elle est beaucoup plus simple à utiliser

**Comment by Jaconil** [comment]
OK pour la version 2.0. Elle est en effet meilleure. Par contre va falloir bien gérer les installs pour les makefile :/

**Comment by Jaconil** [comment]
Cela dit, je sais pas si c'est une bonne idée, la version à installer ne marche pas chez moi, j'ai recompilé la SFML, mais il trouve pas mes bibliothèques maintenant...

**Comment by abisiaux** [comment]
J'ai suivi ce tuto pour recompiler la SFML http://sfmlcoder.wordpress.com/2011/08/16/building-sfml-2-0-with-make-for-gcc/
Tout marche nickel mais attention certains noms de fonctions ont changé comme IsOpened est devenue isOpened => voir la doc sfml2.0

**Comment by Jaconil** [comment]
Oui, sinon il y a ça : http://www.sfml-dev.org/tutorials/2.0/compile-with-cmake.php 
Par contre va falloir compiler la SFML sur chaque ordi sur lequel on veut tester le programme ? Ça va être chiant non ?

**Comment by abisiaux** [comment]
J'ai remarqué aussi un bug au niveau des enum car les valeurs UP, DOWN, LEFT et RIGHT sont contenues dans deux enums différents (EGameKeys et EMenuKeys) et ça ne passe pas au compilateur : UP déjà défini dans ... J'ai pour l'instant modifié EMenuKeys en UP_MENU,...

**Comment by abisiaux** [comment]
Oui je pense qu'il va falloir recompiler la SFML sur les différents ordi mais bon on peut faire un script shell pour ça. Mais bon la 2.0 facilite pas mal de choses...
