### ISSUE TITLE
Fichier de configuration

### ISSUE THREAD

**Issue by abisiaux** [siwon/projetBomberman#13]
Je vois pas sous quelle forme stocker la configuration des joueurs sachant qu'il faut stocker le numéro du joueur, le type de contrôleur utilisé, l'action et la touche correspondante et tout ça sous forme de clé : valeur !

**Comment by Jaconil** [comment]
controller.player1.type: keyboard
controller.player1.up: 62 (le numéro de la touche)
...
controller.player2.type: gamepad
controller.player2.up: y-axis1 (enfin un mot-clé que tu interprètes après... genre x-axis, y-axis, button1, ou un numéro de bouton, etc...)

idem pour la wii

**Comment by abisiaux** [comment]
ok merci

**Comment by abisiaux** [comment]
Autre petit question :

Pourquoi ConfigFileManager n'est pas un singleton car il n'y a qu'un seul fichier de config ?

**Comment by Jaconil** [comment]
non, il y a un fichier de configuration général, plus un fichier de conf par skin. C'est pour ça que je l'ai pas mis en singleton il me semble, et que j'ai mis le chemin d'accès en paramètre optionnel au constructeur (d'ailleurs avec le singleton on peut pas mettre de paramètre au constructeur).

**Comment by Jaconil** [comment]
Non ça n'existe pas ^^
C'était pour forcer la classe fille à implémenter un constructeur avec un argument, mais on peut pas je crois, il faudra modifier...

**Comment by Jaconil** [comment]
Paramètre optionnel hein, si on met rien ça redirige vers le fichier de conf principal ;)

**Comment by Jaconil** [comment]
Oui non excuse c'est en java que ça passe, mais surcharge le constructeur. Fais en un sans paramètres, et l'autre avec un ;)

**Comment by abisiaux** [comment]
Juconil, tu peux me dire ce que doit faire la fonction createDefault() de la classe ConfigFileManager ?

**Comment by Jaconil** [comment]
Cette fonction est appelée si le fichier de configuration appelé n'existe pas. Elle crée alors un fichier minimal avec les valeurs par défaut des touches, des fenêtres, etc...

Remplis les valeurs pour les contrôleurs, j'éditerai cette fonction pour mettre les miennes ;)
