### ISSUE TITLE
SFML et 64bits ?

### ISSUE THREAD

**Issue by siwon** [siwon/projetBomberman#19]
La SFML 2.0 possède des parties uniquement en 32 bits ?

**Comment by Jaconil** [comment]
Ah ?

**Comment by Jaconil** [comment]
http://www.sfml-dev.org/download.php#2.0-rc

installe la bonne version ;)

**Comment by siwon** [comment]
Ben justement ... : Mac OS X 32+64 bits - installer 
Il doit y avoir des restes de 32 bits ...

**Comment by siwon** [comment]
Du coup ça me fait quand meme de belles erreurs  :

Undefined symbols for architecture x86_64:
  "_main", referenced from:
      start in crt1.10.6.o
  "PolyBomber::Bonus::Bonus(PolyBomber::Bonus const&)", referenced from:
      __gnu_cxx::new_allocatorPolyBomber::Bonus::construct(PolyBomber::Bonus_, PolyBomber::Bonus const&)in ccyRFpfX.o
      void std::_Construct<PolyBomber::Bonus, PolyBomber::Bonus>(PolyBomber::Bonus_, PolyBomber::Bonus const&)in ccyRFpfX.o
      std::vector<PolyBomber::Bonus, std::allocator<PolyBomber::Bonus> >::_M_insert_aux(__gnu_cxx::__normal_iterator<PolyBomber::Bonus*, std::vector<PolyBomber::Bonus, std::allocator<PolyBomber::Bonus> > >, PolyBomber::Bonus const&)in ccyRFpfX.o
  "PolyBomber::Bonus::~Bonus()", referenced from:
      void std::_DestroyPolyBomber::Bonus(PolyBomber::Bonus_)in ccyRFpfX.o
      std::vector<PolyBomber::Bonus, std::allocator<PolyBomber::Bonus> >::_M_insert_aux(__gnu_cxx::__normal_iterator<PolyBomber::Bonus_, std::vector<PolyBomber::Bonus, std::allocator<PolyBomber::Bonus> > >, PolyBomber::Bonus const&)in ccyRFpfX.o
  "PolyBomber::Location::~Location()", referenced from:
      PolyBomber::Player::~Player()in ccyRFpfX.o
      PolyBomber::Player::~Player()in ccyRFpfX.o
      PolyBomber::Player::Player(PolyBomber::Player const&)in ccyRFpfX.o
      PolyBomber::Player::Player(PolyBomber::Player const&)in ccyRFpfX.o
      PolyBomber::Player::Player(PolyBomber::Location const&)in ccyRFpfX.o
      PolyBomber::Player::Player(PolyBomber::Location const&)in ccyRFpfX.o
      PolyBomber::Player::Player(int, int)in ccyRFpfX.o
      ...
  "PolyBomber::Location::Location(sf::Vector2<int> const&)", referenced from:
      PolyBomber::Player::Player(PolyBomber::Player const&)in ccyRFpfX.o
      PolyBomber::Player::Player(PolyBomber::Player const&)in ccyRFpfX.o
  "PolyBomber::Player::nbJoueur", referenced from:
      PolyBomber::Player::Player(PolyBomber::Player const&)in ccyRFpfX.o
      PolyBomber::Player::Player(PolyBomber::Player const&)in ccyRFpfX.o
      PolyBomber::Player::Player(PolyBomber::Location const&)in ccyRFpfX.o
      PolyBomber::Player::Player(PolyBomber::Location const&)in ccyRFpfX.o
      PolyBomber::Player::Player(int, int)in ccyRFpfX.o
      PolyBomber::Player::Player(int, int)in ccyRFpfX.o
  "PolyBomber::Location::Location(PolyBomber::Location const&)", referenced from:
      PolyBomber::Player::Player(PolyBomber::Location const&)in ccyRFpfX.o
      PolyBomber::Player::Player(PolyBomber::Location const&)in ccyRFpfX.o
  "PolyBomber::Location::Location(int, int)", referenced from:
      PolyBomber::Player::Player(int, int)in ccyRFpfX.o
      PolyBomber::Player::Player(int, int)in ccyRFpfX.o
ld: symbol(s) not found for architecture x86_64
collect2: ld returned 1 exit status
