### ISSUE TITLE
[Controller] Erreur Bluetooth

### ISSUE THREAD

**Issue by Jaconil** [siwon/projetBomberman#20]
Depuis ton dernier commit (que j'ai pullé par erreur), mes compilations ne marchent plus...

Il me dit : 
include/controller/wiic/wiic.h:50: fatal error: bluetooth/bluetooth.h: Aucun fichier ou dossier de ce type

**Comment by Jaconil** [comment]
OK, soit.
Par contre il me trouve une autre erreur dans CWii : 

include/controller/Wiicpp.hpp:38: fatal error: wiic/dataset.h: Aucun fichier ou dossier de ce type

**Comment by Jaconil** [comment]
OK, alors ça compile en commentant la ligne...

Par contre dans ton makefile tu as mis -lwiicpp
Chez moi il ne la reconnait pas, faut il installer quelque chose ??

**Comment by abisiaux** [comment]
Le 19/05/2012 01:10, GUIHAL Maxime a écrit :

> OK, alors ça compile en commentant la ligne...
> 
> Par contre dans ton makefile tu as mis -lwiicpp
> Chez moi il ne la reconnait pas, faut il installer quelque chose ??
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/siwon/projetBomberman/issues/20#issuecomment-5797619
> lwiicpp c'est pour la librairie libwiicpp.so, j'ai mis le path dans le 
> makefile chez moi ça marche bien sinon tu peux copier dans ton 
> répertoire /usr/lib/, la librairie qui se trouve dans le dossier lib.

Pour le bluetooth juste à installer bluetooth avec un apt-get.

Et voilà tout devrait marcher, il y a pas de raison car chez moi c'est 
nickel ! Par contre la wiimote est un peu moins réactive que le clavier, 
on verra durant la phase de test avec le jeu.

**Comment by Jaconil** [comment]
Tu n'as pas oublié de livrer un fichier ?
Car apparemment libwiicpp.so a besoin de libwiic.so, que tu n'as pas fourni

**Comment by Jaconil** [comment]
Ça compile ! J'ai réinstallé WiiC en téléchargeant depuis les sources ;)
Par contre erreur à l'exécution : 
./PolyBomber: error while loading shared libraries: libwiicpp.so: cannot open shared object file: No such file or directory

**Comment by siwon** [comment]
"Et voilà tout devrait marcher, il y a pas de raison car chez moi c'est
nickel ! Par contre la wiimote est un peu moins réactive que le clavier,
on verra durant la phase de test avec le jeu."

Tu es optimiste Bibiz ... parce que pour le moment on a rien étant donné que je n'avance pas à cause d'une #&$€\* d'erreur ...

**Comment by Jaconil** [comment]
Eh, on a un menu !

**Comment by siwon** [comment]
il doit me manquer les trucs de la wii parce que perso ça me met une erreur ...

**Comment by Jaconil** [comment]
Ouais, faut que tu installes WiiC ;) bonne chance ^^

**Comment by siwon** [comment]
Oui, je dois avouer que je suis en mode galère pour installer cette merde ... XD

**Comment by siwon** [comment]
je ne trouve pas le fichier libwiic.so perso ...

**Comment by Jaconil** [comment]
oui oui il manque un fichier, c'est pour ça que je l'avais réinstallé ^^

**Comment by siwon** [comment]
Durant l'installation, le make me dit qu'il manque un fichier bluetooth/bluetooth.h, du coup ça fait une erreur ...

Il est supposé se trouver où ?

**Comment by siwon** [comment]
déjà fait ...

**Comment by siwon** [comment]
pas mieux (en plus elle était déjà installée ...)

**Comment by Jaconil** [comment]
Non non libbluetooth3 ne fournit que les librairies binaires, pour les .h il faut installer libbluetooth-dev ;)
Bibiz j'espère que tu l'as bien marqué dans ton manuel d'installation !

**Comment by siwon** [comment]
C'est bon ! (Ce n'était pas dans le manuel d'installation donc il faudra l'ajouter Bibizz, si tu veux que je le fasse dis-le !). Du coup, il reste le problème du réseau dont tu parlais dans une autre issue maxime ;)

Merci !

**Comment by siwon** [comment]
Il y a pas de problème tkt, c'est pour ça que j'ai tester l'installation en suivant ton manuel d'installation, pour pouvoir le corriger si nécessaire ;)
