### ISSUE TITLE
HHHAAAAAAAAAA !!!!!

### ISSUE THREAD

**Issue by siwon** [siwon/projetBomberman#21]
Bon, j'en peux plus ! 

Quand je compile mes fichiers 1 par 1, que des warnings pour variables non utilisés, par contre, dès que je fais un petit main, j'ai cette putain d'erreur de mes couilles :

Undefined symbols for architecture x86_64:
  "PolyBomber::GameEngineManager::GameEngineManager()", referenced from:
      _main in ccnHwd20.o
  "PolyBomber::GameEngineManager::~GameEngineManager()", referenced from:
      _main in ccnHwd20.o
ld: symbol(s) not found for architecture x86_64
collect2: ld returned 1 exit status

Je ne sais pas comment m'en débarrasser et ça m'empêche d'avancer ... (sachant que je ne suis même pas au début de ce que je devrais faire ... )

**Comment by siwon** [comment]
Bon ben devant l'aide apportée par chacun, je recommence tous mes fichiers à zéro... (on s'étonnera pas d'avoir encore plus de retard dans le projet )

**Comment by siwon** [comment]
Bonne nouvelle ! Après avoir tout re-coder, l'erreur est toujours présente !!!

**Comment by Jaconil** [comment]
g++ _.o -lsfml-window -lsfml-graphics -lsfml-system
gameEngine_Board.o: In function `PolyBomber::Board::~Board()':
Board.cpp:(.text+0xae0): undefined reference to`PolyBomber::Box::~Box()'
gameEngine_Board.o: In function `PolyBomber::Board::~Board()':
Board.cpp:(.text+0xdb6): undefined reference to`PolyBomber::Box::~Box()'
gameEngine_Board.o: In function `void std::_DestroyPolyBomber::Box(PolyBomber::Box_)':
Board.cpp:(.text._ZSt8_DestroyIN10PolyBomber3BoxEEvPT_[void std::_DestroyPolyBomber::Box(PolyBomber::Box*)]+0xd): undefined reference to `PolyBomber::Box::~Box()'
gameEngine_GameEngineManager.o: In function`PolyBomber::GameEngineManager::getBoard()':
GameEngineManager.cpp:(.text+0x78c): undefined reference to `PolyBomber::Board::boardToSBoard()'
gameEngine_GameEngineManager.o:(.rodata._ZTVN10PolyBomber17GameEngineManagerE[vtable for PolyBomber::GameEngineManager]+0x1c): undefined reference to`PolyBomber::GameEngineManager::getKeysPressed()'
gameEngine_GameEngineManager.o:(.rodata._ZTVN10PolyBomber17GameEngineManagerE[vtable for PolyBomber::GameEngineManager]+0x20): undefined reference to `PolyBomber::GameEngineManager::isPaused()'
gameEngine_GameEngineManager.o:(.rodata._ZTVN10PolyBomber17GameEngineManagerE[vtable for PolyBomber::GameEngineManager]+0x44): undefined reference to`non-virtual thunk to PolyBomber::GameEngineManager::getKeysPressed()'
gameEngine_GameEngineManager.o:(.rodata._ZTVN10PolyBomber17GameEngineManagerE[vtable for PolyBomber::GameEngineManager]+0x48): undefined reference to `non-virtual thunk to PolyBomber::GameEngineManager::isPaused()'
gameEngine_Player.o: In function`PolyBomber::Player::Player(float, float)':
Player.cpp:(.text+0x3f): undefined reference to `PolyBomber::Player::nbJoueur'
Player.cpp:(.text+0x4a): undefined reference to`PolyBomber::Player::nbJoueur'
Player.cpp:(.text+0x52): undefined reference to `PolyBomber::Player::nbJoueur'
gameEngine_Player.o: In function`PolyBomber::Player::Player(float, float)':
Player.cpp:(.text+0x1a7): undefined reference to `PolyBomber::Player::nbJoueur'
Player.cpp:(.text+0x1b2): undefined reference to`PolyBomber::Player::nbJoueur'
gameEngine_Player.o:Player.cpp:(.text+0x1ba): more undefined references to `PolyBomber::Player::nbJoueur' follow
collect2: ld returned 1 exit status
