### ISSUE TITLE
[Controller] Erreur de segmentation GamePad

### ISSUE THREAD

**Issue by Jaconil** [siwon/projetBomberman#26]
Quand je fais setPlayerController(P, GAMEPAD);
où P est [1,2,3,4]
et quand il n'y a pas de joysticks de branchés, il me met une erreur de segmentation.

Le problème ne se pose pas quand on met WII et qu'aucune Wii n'est branchée.

**Comment by abisiaux** [comment]
Ça ne vient pas de moi car ça me lance une exception lorsque que je veux assigner un gamepad à un Zoueur alors qu'il n'y en a pas de branché. J'ai fait le test dans mon test_controller

**Comment by Jaconil** [comment]
Ça ne vient pas de moi non plus ;) Ça marche nickel pour les autres, alors ça ne peut venir que de toi, dsl
