### ISSUE TITLE
Bibiz à l'aide

### ISSUE THREAD

**Issue by Jaconil** [siwon/projetBomberman#29]
En fait j'arrive pas à interfacer ta méthode getCharPressed() avec mon menu.
Je sais pas comment faire pour l'arrêter déjà.
Et quand je l'appelle je l'appelle en boucle là, mais du coup ça fait surchauffer le programme donc bon...

**Comment by Jaconil** [comment]
Ok c'est bon j'ai résolu en modifiant ton code. Je vais pusher

**Comment by Jaconil** [comment]
Bon les majuscules ne fonctionnent pas et c'est normal. Ta fonction ne peut pas tester 2 touches en même temps...
Je l'ai un peu modifié pour prendre en compte les espaces et le backspace. 
Un truc que tu pourrais faire si tu as le temps et si c'est possible ça serait de passer par les KeyReleased avec la window, ce qui te permettrait de récupérer la touche Maj...

**Comment by abisiaux** [comment]
J'ai changé la fonction getCharPressed pour qu'elle marche en event donc ça gère les majuscules maintenant. Par contre c'est assez long la saisie du nom n'aurais tu pas mis un sleep dans ton code ?

**Comment by Jaconil** [comment]
non j'ai mis aucun sleep
