### ISSUE TITLE
Test de recette

### ISSUE THREAD

**Issue by siwon** [siwon/projetBomberman#3]
Il faudrait faire rapidement les test de recette. Le truc c'est que je ne vois pas comment on pourrait présenter ça, ni même le contenu d'ailleurs...

**Comment by Jaconil** [comment]
Je finis de corriger le CdC et je viendrai t'aider à le faire après mon rdv.
Il ne doit pas être très long, 2 pages suffiront à mon avis...

**Comment by Jaconil** [comment]
Avant de modifier, voici ce que j'aurais modifié :

Tests réseau :

un seul test suffit (2 ou 4 ordis)

Tests graphiques :

OK

Tests des contrôleurs :

pour le clavier : un seul test
OK pour le reste

Jouabilité : 

Testable sur le test du clavier ou de l'interface graphique non ?

Conclusion : 

Dire que le client pourra demander tout test supplémentaire

**Comment by siwon** [comment]
Tests réseau :
un seul test suffit (2 ou 4 ordis)

Tests graphiques :
OK

Tests des contrôleurs :
pour le clavier : un seul test ==> CORRIGÉ
OK pour le reste

Jouabilité :
Testable sur le test du clavier ou de l'interface graphique non ? => Oui je suis d'accord avec toi mais le truc c'est qu'on effectuera pas forcément tous les tests, on dit juste ceux qui doivent être satisfait afin de déterminer si cette partie fonctionne. En gros, ce test sera réalisé en même temps que les autres.

Conclusion :
Dire que le client pourra demander tout test supplémentaire => DONE

**Comment by siwon** [comment]
D'autres commentaires ? Perso je ne vois pas trop quoi rajouter ...
