### ISSUE TITLE
[URGENT] Date soutenance

### ISSUE THREAD

**Issue by siwon** [siwon/projetBomberman#31]
J'ai envoyé un mail au prof, afin d'être sur des dates comme vous l'avez vu.
Comme vous l'avez aussi vu, il est dispo lundi aprem, mercredi et vendredi.

Pour le moment je lui ai dit que ce serait vendredi, parce que ça m'arrange perso mais ce n'est pas définitif. Donc êtes-vous d'accord avec le jour et si oui quelle heure vous conviendrait le mieux ? Si vous n'êtes pas d'accord avec la date, dites le moi au plus tôt afin que je corrige le tir !

Répondez au plus vite SVP !

**Comment by Jaconil** [comment]
idem, même si le projet devra être rendu vendredi prochain normalement...
Au pire on aura des beaux slides ^^

**Comment by siwon** [comment]
"Nickel vendredi matin ça nous laisse le temps de bien finir le projet" => Bibiz, le projet aura déjà été rendu. Il faut qu'il soit terminé pour dimanche 3 Juin avant minuit comme dit dans le mail !

**Comment by siwon** [comment]
Ok, j'avais mal compris ;) My mistake ! (<= et ouais j'ai le TOEIC ! XD)

**Comment by siwon** [comment]
Brice tu nous donnera ton avis aussi ;)

**Comment by Jaconil** [comment]
Brice m'a dit qu'il était totalement ok pour cette date.
