### ISSUE TITLE
©

### ISSUE THREAD

**Issue by Jaconil** [siwon/projetBomberman#33]
Enlève moi tt de suite ce truc commercial qui n'a rien à voir avec un projet scolaire...

**Comment by siwon** [comment]
Je crois qu'il parle des copyright que tu as ajouté

**Comment by Jaconil** [comment]
C'est pas que c'est pas scolaire, c'est juste que ça n'a rien à faire là : http://fr.wikipedia.org/wiki/Copyright ...
Déjà que notre projet n'est pas légal vis-à-vis des images qu'on utilise qui sont sous propriété de Hudson Soft, alors si en plus on commence à copyrighter le nom ou le programme....

Pourquoi pas le vendre non plus ? (dédicasse à Brice)

**Comment by abisiaux** [comment]
D'ailleurs c'est ce qu'on a décidé avec stunt, faut qu'on fixe le prix.

**Comment by siwon** [comment]
Faudrait vraiment être con pour vouloir le vendre ... Brice je ne pense pas que ce soit une bonne idée ... Un système de location avec un abonnement serait bien plus intelligent et pourrait nous rapporter beaucoup plus XD

**Comment by abisiaux** [comment]
Pas con la location on va en parler à pica !

**Comment by siwon** [comment]
Ben oui parce qu'il devra payer pour pouvoir le tester donc va falloir le prévenir ...

**Comment by abisiaux** [comment]
Je pense qu'on va lui faire tester la démo (avec juste le menu) puis 
s'il en veut plus faudra sortir les pépettes!

**Comment by siwon** [comment]
Ouais pas bete, comme ça on créé la dépendance, et après on fait payer !
