### ISSUE TITLE
SFML et manuel d'installation

### ISSUE THREAD

**Issue by siwon** [siwon/projetBomberman#35]
Je suis partit d'une installation pratiquement vierge de Ubuntu et je suivis ton manuel d'installation mais je n'arrive pas à compiler le projet. Il me dit des messages du type :
...
WaitingMenu.cpp:(.text+0x2fa): undefined reference to `sf::Text::setColor(sf::Color const&)'
...
Etant donné que j'ai installé SFML 2.0 je ne comprend pas trop pourquoi il ne trouve pas ces fichiers ...  une idée ?

**Comment by Jaconil** [comment]
Oui oui, refais un pull et recommence, c'est pas une erreur d'installation, mais de linkage dû à moi sûrement.

**Comment by siwon** [comment]
Je pense quand meme qu'il manque des étapes ... Je me demande si il ne faut pas installer la SFML 1.6 puis la SFML 2.0

**Comment by Jaconil** [comment]
Non, au contraire ça génèrera des conflits

**Comment by siwon** [comment]
Ok

**Comment by siwon** [comment]
Je viens de faire un fichier install.sh afin de normalement tout installer pour que tout puisse fonctionner.

Par contre, faut faire attention à ne pas pusher après avoir tout installé parce que je crois que ça créé pas mal de fichiers ... Faut que je vérifie tout ça !

**Comment by abisiaux** [comment]
Je ne pense pas qu'il faille installer wiic car les librairies sont déjà 
dans le dossier lib et dans le makefile j'ai précisé le répertoire où 
les chercher. Il n'y a rien à faire normalement pour la wii. Sinon pour 
la sfml 2.0, juconil ne voulait pas la mettre dans le projet...

**Comment by abisiaux** [comment]
ok pour la sfml j'avais pas vu qu'elle était déjà sur github sinon pour 
wiic enlève tout ça mets juste libwiic.so et libwiicpp.so ça ne sert à 
rien de les faire générer.

**Comment by siwon** [comment]
Justement, il faut les faire générer ! Quand je prenais les tiennes, il me mettait que le type était incompatible, du coup ça ne compilait pas ...

C'est pour ça que je les regénère ;)

**Comment by abisiaux** [comment]
Je savais pas je pensais que la librairie était portable sur tout linux 
sans avoir à la régénérer. Du coup faut reprendre le manuel d'installation.

**Comment by siwon** [comment]
ouaip désolé pour le boulot supplémentaire ... Par contre, je pense que le ./install.sh on peut le mettre dans le makefile ... avec un truc genre make install 

Après je connais rien au makefile ...

**Comment by abisiaux** [comment]
Je le reprends n'y touche pas stp pour l'instant ;-)

**Comment by abisiaux** [comment]
oui on peut je m'en occupe

**Comment by siwon** [comment]
Ok !
