### ISSUE TITLE
wiic/wiic.h

### ISSUE THREAD

**Issue by siwon** [siwon/projetBomberman#36]
A la compilation :

include/controller/Wiicpp.hpp:37:23: error: wiic/wiic.h: Aucun fichier ou dossier de ce type

**Comment by abisiaux** [comment]
Lol maxime a voulu tout supprimer du dossier d'include et bah voilà ça 
fait de la merde maintenant !

Sinon j'ai continué le manuel d'install, le delete.sh c'est pour 
supprimer les fichiers produits par l'installation de la sfml ?

**Comment by siwon** [comment]
Peut-être que les librairies que tu inclus sont dans le XiiC que j'ai ajouté, (même surement) donc fait le lien ...

Sinon, le delete.sh, oui mais c'est un test plutôt un test pour le moment, si ça fonctionne bien, je l’intégrerais au install.sh ;)

**Comment by abisiaux** [comment]
Ok tu feras appel au delete.sh dans le install.sh donc pour le manuel 
c'est ok ?
J'ai corrigé le lien de la librairie mais je peux pas voir si ça marche 
car ça ne compile pas du tout chez moi il manque des fichiers.

**Comment by siwon** [comment]
qu'est ce qui ne compile pas ?

Et perso, je pense qu'il vaudrait mieux faire une commande :
make install 
pour lancer l'installation de toutes les librairies et genre le "make install" lance le "./install.sh"

**Comment by abisiaux** [comment]
J'ai regardé pour le make install je pense pas que ça soit 
possible...tant pis

**Comment by siwon** [comment]
Pas grave ... peut-être que maxime saura faire ... 

Sinon c'est quoi les fichiers qu'il te manque ?

**Comment by abisiaux** [comment]
Nan c'est pas des fichiers c'est une erreur de compilation :
     NetworkManager.cpp l621 : cannot call constructor 
sf::IpAddress::IpAddress
après le reste c'est juste des warnings!
