### ISSUE TITLE
[Controller] Multitouches

### ISSUE THREAD

**Issue by Jaconil** [siwon/projetBomberman#39]
Pendant une partie, lorsque le joueur 1 appuie sur une touche, le joueur 2 ne peut pas appuyer sur une autre touche.
En gros, tu gères pas les multi touches pendant la partie...

**Comment by abisiaux** [comment]
push stp que j'essaie de résoudre ça

**Comment by abisiaux** [comment]
Putain je viens de faire avec les events c'est toujours pareil ça gère 
pas le multitouches !!!

**Comment by abisiaux** [comment]
Je pense avoir trouver :

void sf::Window::setKeyRepeatEnabled    (   bool    /enabled/   )   

Enable or disable automatic key-repeat.

If key repeat is enabled, you will receive repeated KeyPressed events 
while keeping a key pressed. If it is disabled, you will only get a 
single event when the key is pressed.

Key repeat is enabled by default.

_Parameters:_
    enabled     True to enable, false to disable

**Comment by Jaconil** [comment]
ça doit être ça

**Comment by abisiaux** [comment]
Je pense avoir réglé le soucis, je met au propre car du coup c'est le 
bordel et je push!
