### ISSUE TITLE
Déplacement perso

### ISSUE THREAD

**Issue by abisiaux** [siwon/projetBomberman#40]
Je viens de tester les contrôleurs pour déplacer les persos :

Clavier => No Problem
Joystick => No Problem
Wiimote => probleme ! C'est très lent vous avez du mettre un sleep trop élevée dans la boucle de jeu, moi j'avais mis 5ms dans le menu pour pas que ça affecte de trop la wiimote si vous pouvez faire pareil.

Sinon pour le multi touches ça marche très bien maintenant c'est formidable !

Et super la bombe qui explose le programme ^^

**Comment by abisiaux** [comment]
c'est bon j'ai trouvé c'est dans gameenginemanager.cpp l235 en changeant 50 par 5 nickel!

**Comment by Jaconil** [comment]
On s'en fout de ta Wii, t'avais qu'à venir avec nous débugguer le moteur de jeu cet aprem !!

**Comment by abisiaux** [comment]
Merci c'est sympa en tout cas cet aprem j'ai pas glander non plus !
