### ISSUE TITLE
[Bibiz] Flamme centrale

### ISSUE THREAD

**Issue by Jaconil** [siwon/projetBomberman#41]
T'as oublié de fournir une image pour l'origine des flammes ^^

Sinon j'ai pas compris la différence entre :
- flame_begin_horizontal.png
- flame_middle_horizontal.png

**Comment by abisiaux** [comment]
J'ai repris l'image que Simon m'a dit de prendre dans le dossier test. 
flamme_begin est un poil plus petite que flamme middle et l'origine des 
flammes c'était flamme begin comme sur l'exemple. On peut mettre aussi 
comme origine la même image que celle de la fin.

Sinon c'était pas une raison de m'envoyer chier tout à l'heure, je pense 
que je me suis quand même investi dans ce projet. Aujourd'hui j'ai passé 
l'aprem sur photoshop à faire un joli skin comme vous m'avez demandé et 
on était d'accord pour intégrer la wiimote au jeu, j'ai passé beaucoup 
de temps là dessus c'est pas pour me dire maintenant que vous vous en 
foutez!

**Comment by Jaconil** [comment]
Désolé pour tout à l'heure, on est tous un peu sur les nerfs en ce moment tu sais... Et j'ai pas dit que tu t'investissais pas, au contraire, t'as refais tout le skin et tout et c'est vraiment pas mal...

Pour l'origine en fait, j'entendais par là l'image des flammes à une intersection (en gros toute la case en flamme, pour que ça se raccorde aux autres)
