### ISSUE TITLE
URGENT

### ISSUE THREAD

**Issue by siwon** [siwon/projetBomberman#44]
Il faut supprimer tous les messages d'affichage que vous avez fait dans vos fichiers !!! On ne peut pas rendre le projet comme ça !

**Comment by siwon** [comment]
En fait, vous les avez presque tous foutus dans ma partie quoi ... XD

**Comment by siwon** [comment]
Il en reste quelques-uns quand même surement dans ta partie juconil

**Comment by Jaconil** [comment]
Oui oui tkt pas j'allais le faire cet après-midi, j'ai pas fini de nettoyer mon code, ni de le commenter

**Comment by Jaconil** [comment]
Garde-ton le répertoire tests ??

**Comment by siwon** [comment]
Ben le supprime pas, mais on est pas obligé de le rendre au prof.
