### ISSUE TITLE
fichier de conf

### ISSUE THREAD

**Issue by Jaconil** [siwon/projetBomberman#46]
Bibiz, 
Brice est en train de tester le programme, et à chaque erreur de segmentation, ton fichier est vidé, 
Y a vraiment pas moyen que tu écrives au fur et à mesure dedans, plutot qu'à la fin ?

Car là du coup c'est chiant...

**Comment by abisiaux** [comment]
Je suis pas chez moi dsl ça doit être dans close file dans configfilemanager car je le recouvre en écrasant l'ancien donc faudrait juste le rouvrir en ajout. Si tu peux le faire stp car là je peux vraiment pas j'ai rien pour le faire dsl.

Envoyé depuis un mobile Samsung

GUIHAL Maxime reply@reply.github.com a écrit :

Bibiz, 
Brice est en train de tester le programme, et à chaque erreur de segmentation, ton fichier est vidé, 
Y a vraiment pas moyen que tu écrives au fur et à mesure dedans, plutot qu'à la fin ?

Car là du coup c'est chiant...

---

Reply to this email directly or view it on GitHub:
https://github.com/siwon/projetBomberman/issues/46

**Comment by Jaconil** [comment]
OK OK pas de prob
