### ISSUE TITLE
Prix de vente du programme

### ISSUE THREAD

**Issue by Jaconil** [siwon/projetBomberman#47]
Totals grouped lines by language (dominant language first):
cpp:           8970 (97.12%)
sh:             266 (2.88%)

Total Physical Source Lines of Code (SLOC)                = 9,236
Schedule Estimate, Years (Months)                         = 0.71 (8.47)
Total Estimated Cost to Develop                           = $ 278,869

C'est bon les gars, on peut le vendre à 279$ notre Bomberman !!

**Comment by Guillermicb** [comment]
Du moment que total débit = total crédit ça me va

**Comment by siwon** [comment]
Ben vu les conneries qu'on a débité, il va falloir augmenter le total crédit !
