### ISSUE TITLE
Détonateur (pour Bibizz et Brice)

### ISSUE THREAD

**Issue by Jaconil** [siwon/projetBomberman#5]
Dilemme entre Simon et moi concernant le bonus "Détonateur"  qui permet de faire exploser toutes ses bombes en même temps en appuyant sur Action2.

En gros la question c'est : Faut-il rendre ce bonus permanent ou non ?

**Point de vue de Simon :**

Soit ce bonus est permanent, c'est à dire qu'une fois acquis on garde toujours le détonateur et qu'il faut toujours appuyer sur Action2 pour faire exploser nos bombes. Mettre une probabilité faible à ce bonus.

Soit le bonus correspond à une "bombe télécommandée" où le détonateur n'agit que sur une seule bombe, mais où ce bonus prend fin après une utilisation.

**Point de vue de Maxime :**

Ce bonus prend fin après avoir appuyé sur le détonateur et fait exploser toutes ses bombes. Cela permet de ne pas avantager trop un joueur par rapport aux autres.

Utiliser la touche Action2 également pour déposer une mine,  et pour le bonus "Ligne de bombes", de la façon suivante :
- Si on a le détonateur et qu'on prend un bonus Mine : on perd le détonateur et nos bombes explosent.
- Si on a le bonus Mine et qu'on prend le détonateur, on perd le bonus Mine.
- Idem pour "Ligne de bombes"

Quel est votre avis là-dessus ?

**Comment by siwon** [comment]
Pour résumer mon avis, la grosse différence selon moi est là suivante :
- Soit c'est une bombe télécommandée : il y a donc un usage unique à la bombe,
- Soit c'est une télécommande : il y a donc un usage permanent.

**Comment by Guillermicb** [comment]
Pour moi, usage permanent et faible quantité :) C'est un avantage mais ça devient très tactique et c'est pas toujours évident. Et puis on peut aussi se faire péter la gueule

**Comment by Jaconil** [comment]
Ok pour ça alors...

Du coup pour les mines on fait comment ?
Obligé de poser la mine avant de poser une autre bombe ?

**Comment by siwon** [comment]
Oui. 
Par contre, le détonateur il déclenche les mines aussi ou pas ?

**Comment by Jaconil** [comment]
Non

**Comment by abisiaux** [comment]
Usage permanent pour moi aussi dsl les gars j'étais très occupé aujourd'hui... Faut surtout mettre une faible proba pour ce bonus car la partie peut très vite se terminer sinon.
Le détonateur ne déclenche que les bombes et non les mines. Les mines ne pètent que lorsqu'on passe dessus.

**Comment by siwon** [comment]
Tkt on a la réponse de tout le monde, ça nous va ;)
Sinon pour les pourcentages, ils sont tous enregistrés.
