### ISSUE TITLE
Puddi Puddi

### ISSUE THREAD

**Issue by siwon** [siwon/projetBomberman#51]
Tout est dans le titre ...

**Comment by 64q** [comment]
Puddi !

**Comment by siwon** [comment]
Je suis content de voir que le message est compris ;)

**Comment by Jaconil** [comment]
Faut vraiment que je remette en route mon lecteur de flux RSS sur Github...

**Comment by siwon** [comment]
C'est sur que ce serait dommage de rater des issues pareilles ;)

**Comment by Jaconil** [comment]
Je conteste la fermeture de cette issue, l'anomalie Puddi Puddi est toujours présente chez toi @siwon...

**Comment by siwon** [comment]
-__-
