### ISSUE TITLE
Dates à définir

### ISSUE THREAD

**Issue by siwon** [siwon/projetBomberman#6]
Il faut définir les dates suivantes :
- Date de rencontre avec le client
- Date prévue pour une réunion du groupe pour la conception générale du système
- Date prévue de rendu de la fiche 3

Donc donnez moi votre avis.

**Comment by abisiaux** [comment]
Date de rencontre avec le client c'est la date à laquelle on a vu le prof, il y a juste deux dates à définir, pour la fiche 3 il y a pas mal de boulot à faire à ce que j'ai lu donc il serait préférable de se laisser au moins 2 semaines pour faire toute la modélisation. Pour la réunion de groupe on peut donner une date bidon de toute façon on va bosser tout au long de la semaine et surtout durant les cours de .....
Enfin je propose Vendredi 23 Mars

**Comment by Jaconil** [comment]
23 mars c'est bcp trop tôt bibizz...
regarde là pour le CDCF on a déjà passé 2 semaines alors que c'était simple.

Là il faut faire TOUTE la modélisation, faut repousser à début avril. (surtout qu'on a exam d'optimisation, c++, géo algo)

**Comment by siwon** [comment]
13 avril ?

**Comment by Jaconil** [comment]
Juste avant les vacs.
Ok pour moi.

**Comment by abisiaux** [comment]
ok pour le 13 avril c'est vrai qu'on a beaucoup d'examens .

**Comment by siwon** [comment]
Reste celle-ci : Date prévue pour une réunion du groupe pour la conception générale du système

Je ne sais pas trop à quoi elle correspond par contre ...
