### ISSUE TITLE
Titre cahier des charges

### ISSUE THREAD

**Issue by Jaconil** [siwon/projetBomberman#7]
J'ai modifié le titre du cahier des charges en rajoutant "Fonctionnel" pour le différencier du Cahier des charges technique qu'on aura aussi à faire...

Mais du coup ça merde pour l'alignement du titre. Donc je sais pas trop, soit on le met en sous-titre plutôt, sur 2 lignes peut-être.

**Comment by abisiaux** [comment]
C'est corrigé!
