### ISSUE TITLE
URGENT : Modification CdC

### ISSUE THREAD

**Issue by siwon** [siwon/projetBomberman#8]
Je propose une modification concernant la durée de la mèche. Passer au moins de 2 à 3 secondes puisque si les bonus s'accumulent (genre explosion en 8 connexité + longue portée) le mec dès qu'il va poser une bombe il va se tuer ... 

D'accord oui ou non ?

**Comment by Jaconil** [comment]
d'accord pour 3 secondes

**Comment by abisiaux** [comment]
3 secondes le temps de bien s'arracher le cul de là

**Comment by siwon** [comment]
Bon on part sur 3 secondes !

@Guillermicb : si tu as une objection tu rouvres ce topic avant ce soir !
